name: CAS Repository Docker Build Workflow
on: 
  workflow_dispatch:
    inputs:
      image-types:
        description: 'Image types to build'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - standard
          - cuda
      docker-tag:
        description: 'Docker image tag. Will use the last commit hash if nothing is passed in'
        required: true
      
      
jobs:

  update-docker-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
    env:
      DOCKER_REGISTRY_NAME: us-central1-docker.pkg.dev
      PYTORCH_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cas-services-cicd/cas-pytorch
      PYTORCH_CUDA_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cas-services-cicd/cas-pytorch-cuda
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/docker-build
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          pytorch-image-name: ${{ env.PYTORCH_IMAGE_NAME }}
          pytorch-cuda-image-name: ${{ env.PYTORCH_CUDA_IMAGE_NAME }}
          image-tag: ${{ inputs.docker-tag }}
          image-types: ${{ inputs.image-types }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
